//created on: 8 nov. 2020
package dsiRules

//list any import classes here.

import clasesMito.*;
import clasesMito.acciones.*;
import clasesMito.estados.*;
import clasesMito.Personajes.*;
import java.util.List;
import java.util.LinkedList;

//declare any global variables here

//REGLAS DESDE EL PRINCIPIO

//1º REGLA: TODOS LOS PERSONAJES LIBRES : 
rule "personajes libres y vivos"

    when
        //conditions y definimos variable $p
      	$p : Personaje();
      	not Muerto();
    then
        //actions
        if ($p.getNombre() != "Ceto"){
        	Estado libre = new Libre($p);
        	insert(libre);
        }else {
        	Estado presoCeto  = new Preso($p);
        	insert(presoCeto);
        }
		Estado vivo = new Vivo($p);
		insert(vivo);
		
end

//1.1 Regla: llenar inventario vacios
rule "llenar inventarios vacios"
	when
		$p: Personaje(inventario == null); 
	then
		$p.setInventario(new LinkedList<Objeto>());
		update($p);
end

//2º REGLA: casiopea enoja a poseidon 
rule "casiopea enoja a poseidon"

    when
      	$a: Enojar(sujeto.nombre == "Casiopea", afectadoP != null, afectadoP.nombre == "Poseidón");
      	$p: Personaje(nombre == "Ceto");
    then
        //actions
        System.out.println($p.getNombre() + " queda libre debido a enojo de " + $a.getAfectadoP().getNombre() + " hacia " + $a.getSujeto().getNombre());
		Accion poseidonLiberaCeto = new Liberar($a.getAfectadoP(), $p);
		Estado libreCeto = new Libre ($p) ;
		insert (poseidonLiberaCeto);
		insert (libreCeto);
			
end
//3º REGLA: andromeda es apresada por ceto

rule "andromeda es apresada por ceto"
	when 
		$e : Libre(sujeto.nombre == "Ceto")
		$p : Personaje(nombre == "Andrómeda")
	then 
		Accion cetoApresaAndromeda = new Apresar($e.getSujeto(), $p);
		Estado andromedaApresada = new Preso($p);
		insert(cetoApresaAndromeda);
		insert(andromedaApresada);
		System.out.println(  $p +" queda presa debido a estar " + $e.getSujeto() + " libre.");
end

//4º REGLA: favores de dioses a Perseo  
rule "favores de dioses a Perseo" 
	when 
		$f : DarFavor($s : sujeto, $a : afectadoP);
	then 
		System.out.println($a.getNombre() + " obtiene " + $s.getInventario().toString() + " debido a tener el favor de " + $s.getNombre());
		$a.getInventario().addAll($s.getInventario());
		for (Objeto o : $s.getInventario()){
			Accion afectadoObtiene = new Obtener($a, o);
			insert(afectadoObtiene);
		}
		$s.setInventario(new LinkedList<Objeto>());
		update($a);
		update($s);
end

//5º REGLA: perseo roba el ojo de las grayas
rule "perseo roba el ojo de las grayas"
	when 
		$mg : Objeto(nombre == "Mapa Grayas");
		$ojo : Objeto(nombre == "Ojo Graya");
		$ch : Objeto(nombre == "Casco Hades");
		$mn : Objeto (nombre == "Mapa Ninfas");
		$g : Personaje(nombre == "Grayas", inventario contains $ojo, inventario contains $mn);
		$p : Personaje(nombre == "Perseo", inventario contains $mg, inventario contains $ch );
	then
		$p.getInventario().add($ojo);
		Accion perseoObtieneOjo = new Obtener($p, $ojo);
		insert(perseoObtieneOjo);
		$g.getInventario().remove($ojo);
		
		System.out.println($p.getNombre() + " roba " +  $ojo.getNombre() + " de " + $g.getNombre() + " debido a tener " + $ch.getNombre() );
		update($p);
		update($g);
end

//6º REGLA: perseo intercambia ojo por mapa ninfa

rule "perseo intercambio ojo por mapa ninfas"
	when
		$mn : Objeto(nombre == "Mapa Ninfas");
		$ojo : Objeto(nombre == "Ojo Graya");
		$g : Personaje(nombre == "Grayas", inventario contains $mn);
		$p : Personaje(nombre == "Perseo", inventario contains $ojo);
	then 
		$p.getInventario().add($mn);
		$g.getInventario().add($ojo);
		$p.getInventario().remove($ojo);
		$g.getInventario().remove($mn);
		Accion perseoObtieneMapaN = new Obtener($p, $mn);
		Accion grayasObtieneOjo = new Obtener($g, $ojo);
		insert(perseoObtieneMapaN);
		insert(grayasObtieneOjo);
		System.out.println($p.getNombre() + " localiza a las ninfas debido a intercambio de " +  $ojo.getNombre() +  " por el " + $mn.getNombre() );
		update($p);
		update($g);
end
//7º REGLA: perseo obtiene inventario ninfas

rule "perseo obtiene inventario ninfas"
	when
		$mn : Objeto (nombre == "Mapa Ninfas");
		$p : Personaje(nombre == "Perseo", inventario contains $mn);
		$n : Personaje (nombre == "NinfasNorte", inventario.empty == false );
	then 
		System.out.println($p.getNombre() + " obtiene " + $n.getInventario().toString() + " debido a tener a las ninfas localizadas.");
		$p.getInventario().addAll($n.getInventario());
		$n.setInventario(new LinkedList<Objeto>());
		for (Objeto o : $n.getInventario()){
			Accion afectadoObtiene = new Obtener($p, o);
			insert(afectadoObtiene);
		}
		update($p);
		update($n);
end

//8º REGLA: Matar a medusa
rule "matar a medusa"
	when
		$ha:Objeto(nombre == "Hoz Acero");
		$ch:Objeto(nombre == "Casco Hades");
		$esc:Objeto(nombre == "Escudo Espejo");
		$sa:Objeto(nombre == "Sandalias Aladas");
		$medusaViva: Vivo(sujeto.nombre == "Medusa");
		$p:Personaje (nombre == "Perseo" , inventario contains $ha, inventario contains $ch, inventario contains $esc, inventario contains $sa);
	then
		System.out.println($p.getNombre() + " mata a  " + $medusaViva.getSujeto().getNombre()  + " debido a tener " + $ha.getNombre() + " " +  
		$ch.getNombre() + " " + $esc.getNombre() + " "+ $sa.getNombre() );
		
		System.out.println($p.getNombre() + " obtiene " + $medusaViva.getSujeto().getInventario().toString() + " debido a matar a " + $medusaViva.getSujeto().getNombre());
		
		Accion perseoMataMedusa = new Matar($p, $medusaViva.getSujeto());
		Estado medusaMuerta = new Muerto($medusaViva.getSujeto());
		for (Objeto o : $medusaViva.getSujeto().getInventario()){
			Accion afectadoObtiene = new Obtener($p, o);
			insert(afectadoObtiene);
		} 
		$p.getInventario().addAll($medusaViva.getSujeto().getInventario());
		$medusaViva.getSujeto().setInventario(new LinkedList<Objeto>());
		
		insert(medusaMuerta);
		insert(perseoMataMedusa);
		update($p);
		update($medusaViva.getSujeto());
		retract($medusaViva);	
end

//9º REGLA: Matar a ceto
rule "matar a ceto"
	when
		$p : Personaje (nombre == "Perseo");
		$cm: Objeto(nombre == "Cabeza Medusa") from $p.inventario;
		$cetoVivo : Vivo(sujeto.nombre == "Ceto");
		$andromedaPresa : Preso(sujeto.nombre == "Andrómeda");
		
	then 
		System.out.println($p.getNombre() + " mata a " + $cetoVivo.getSujeto().getNombre() + " debido a tener " + $cm.getNombre());
		System.out.println($p.getNombre() + " libera a " + $andromedaPresa.getSujeto().getNombre() + " debido a matar a " + $cetoVivo.getSujeto().getNombre());
		Accion perseoMataCeto = new Matar($p, $cetoVivo.getSujeto());
		Estado cetoMuerto = new Muerto($cetoVivo.getSujeto());
		Accion liberarAndromeda = new Liberar($p, $andromedaPresa.getSujeto());
		Estado andromedaLibre = new Libre($andromedaPresa.getSujeto());
		
		insert (perseoMataCeto);
		insert(cetoMuerto);
		insert(liberarAndromeda);
		insert (andromedaLibre);
		
		retract ($andromedaPresa);
		retract($cetoVivo);
end